=== axonivy-market/market/schema/meta.json
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "$defs" : {
    "ArchivedArtifact" : {
      "type" : "object",
      "properties" : {
        "artifactId" : {
          "type" : "string",
          "minLength" : "5"
        },
        "groupId" : {
          "type" : "string",
          "minLength" : "5"
        },
        "lastVersion" : {
          "type" : "string",
          "description" : "this is the 'max version' selector. All versions which are lower than or equal the defined value, will be treated as legacy artifact.\nTherefore supplying 'legacy' group-/artifact-id for download.\n",
          "minLength" : "5"
        }
      },
      "required" : [ "artifactId", "groupId", "lastVersion" ],
      "additionalProperties" : false
    },
    "ArtifactType" : {
      "type" : "string",
      "enum" : [ "zip", "nbm", "jar" ]
    },
    "Cost" : {
      "type" : "string",
      "enum" : [ "free", "paid" ]
    },
    "DisplayDescription" : {
      "type" : "object",
      "properties" : {
        "locale" : {
          "minLength" : "2",
          "additionalProperties" : false,
          "type" : "string",
          "examples" : [ "{'de', 'en'}" ]
        },
        "value" : {
          "type" : "string",
          "minLength" : "5",
          "maxLength" : "200"
        }
      },
      "required" : [ "locale", "value" ],
      "additionalProperties" : false
    },
    "DisplayName" : {
      "type" : "object",
      "properties" : {
        "locale" : {
          "minLength" : "2",
          "additionalProperties" : false,
          "type" : "string",
          "examples" : [ "{'de', 'en'}" ]
        },
        "value" : {
          "type" : "string",
          "minLength" : "1",
          "maxLength" : "30"
        }
      },
      "required" : [ "locale", "value" ],
      "additionalProperties" : false
    },
    "MavenArtifact" : {
      "type" : "object",
      "properties" : {
        "archivedArtifacts" : {
          "description" : "archived artifacts using old (legacy) group ID and artifact ID with the last version they were being used.",
          "type" : "array",
          "items" : {
            "$ref" : "#/$defs/ArchivedArtifact"
          },
          "examples" : [ " \t\t\"archivedArtifacts\": [\n\t{\n\t\t\"lastVersion\": \"10.0.0\",\n\t\t\"groupId\": \"com.axonivy.connector.twitter\",\n\t\t\"artifactId\": \"twitter-connector\"\n\t}\n]\n" ]
        },
        "artifactId" : {
          "type" : "string",
          "minLength" : "5"
        },
        "doc" : {
          "type" : "boolean"
        },
        "groupId" : {
          "type" : "string",
          "minLength" : "5"
        },
        "key" : {
          "type" : "string"
        },
        "makesSenseAsMavenDependency" : {
          "type" : "boolean"
        },
        "name" : {
          "type" : "string",
          "minLength" : "5"
        },
        "repoUrl" : {
          "type" : "string"
        },
        "type" : {
          "$ref" : "#/$defs/ArtifactType"
        }
      },
      "required" : [ "artifactId", "groupId", "name" ],
      "additionalProperties" : false
    },
    "Type" : {
      "type" : "string",
      "enum" : [ "connector", "demo", "utils", "solution" ]
    }
  },
  "type" : "object",
  "properties" : {
    "$schema" : {
      "type" : "string"
    },
    "compatibility" : {
      "type" : "string",
      "pattern" : "^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)[+]?$"
    },
    "contactUs" : {
      "type" : "boolean",
      "description" : "shows the link to contact axonivy"
    },
    "cost" : {
      "$ref" : "#/$defs/Cost"
    },
    "deprecated" : {
      "type" : "boolean"
    },
    "description" : {
      "type" : "string",
      "minLength" : "5",
      "maxLength" : "200"
    },
    "descriptions" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/$defs/DisplayDescription"
      }
    },
    "id" : {
      "type" : "string",
      "minLength" : "5",
      "maxLength" : "30"
    },
    "industry" : {
      "minLength" : "2",
      "additionalProperties" : false,
      "type" : "string",
      "examples" : [ "Cross-Industry" ]
    },
    "installMatcher" : {
      "type" : "string",
      "examples" : [ "best-match" ]
    },
    "language" : {
      "type" : "string",
      "examples" : [ "English" ]
    },
    "listed" : {
      "type" : "boolean"
    },
    "mavenArtifacts" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/$defs/MavenArtifact"
      }
    },
    "name" : {
      "type" : "string",
      "minLength" : "4",
      "maxLength" : "24"
    },
    "names" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/$defs/DisplayName"
      }
    },
    "platformReview" : {
      "type" : "string",
      "pattern" : "^([0-4])?(\\.[5])?$|^5$"
    },
    "sourceUrl" : {
      "type" : "string",
      "format" : "uri",
      "examples" : [ "https://github.com/axonivy-market/acme-connector" ]
    },
    "statusBadgeUrl" : {
      "type" : "string",
      "format" : "uri",
      "examples" : [ "https://github.com/axonivy-market/acme-connector/actions/workflows/ci.yml/badge.svg" ]
    },
    "tags" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "type" : {
      "$ref" : "#/$defs/Type"
    },
    "validate" : {
      "type" : "boolean"
    },
    "vendor" : {
      "type" : "string",
      "minLength" : "3"
    },
    "vendorImage" : {
      "type" : "string",
      "description" : "relative path to a logo of the vendor, e.g. 'acme.png'"
    },
    "vendorImageDarkMode" : {
      "type" : "string",
      "description" : "relative path to a logo of the vendor dark mode, e.g. 'acme-dark-mode.png'"
    },
    "vendorLogo" : {
      "type" : "string",
      "description" : "relative path to a badge of the vendor, e.g. 'bagde.png'"
    },
    "vendorLogoDarkMode" : {
      "type" : "string",
      "description" : "relative path to a badge of the vendor dark mode, e.g. 'bagde-dark.png'"
    },
    "vendorUrl" : {
      "type" : "string",
      "format" : "uri",
      "description" : "public accessible URI representating the vendor"
    },
    "version" : {
      "type" : "string",
      "pattern" : "^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$"
    },
    "versionDisplay" : {
      "type" : "string"
    }
  },
  "required" : [ "description", "id", "name", "type" ],
  "additionalProperties" : false
}

=== axonivy-market/market/market/connector/stripe-connector/meta.json
{
    "$schema" : "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
    "id" : "stripe-connector",
    "name" : "Stripe",
    "names" : [
        {
            "locale" : "en",
            "value" : "Stripe"
        },
        {
            "locale" : "de",
            "value" : "Stripe"
        }
    ],
    "description" : "Stripe is a comprehensive payment processing platform that enables businesses to accept payments online and in-person.",
    "descriptions" : [
        {
            "locale" : "en",
            "value" : "Stripe is a comprehensive payment processing platform that enables businesses to accept payments online and in-person."
        },
        {
            "locale" : "de",
            "value" : "Stripe ermöglicht es dir, Zahlungen über eine flexible Plattform sowohl online als auch im direkten Kontakt zu akzeptieren."
        }
    ],
    "type" : "connector",
    "platformReview" : "5",
    "sourceUrl" : "https://github.com/axonivy-market/stripe-connector",
    "statusBadgeUrl" : "https://github.com/axonivy-market/stripe-connector/actions/workflows/ci.yml/badge.svg",
    "language" : "English",
    "industry" : "Cross-Industry",
    "tags" : [
        "Payment"
    ],
    "mavenArtifacts" : [
        {
            "repoUrl" : "https://maven.axonivy.com",
            "name" : "Stripe Connector",
            "groupId" : "com.axonivy.connector.stripe",
            "artifactId" : "stripe-connector-product",
            "type" : "zip"
        }
    ]
}

=== axonivy-market/market/market/utils/microsoft365/calendar/meta.json
{
  "$schema": "https://json-schema.axonivy.com/market/10.0.5/meta.json",
  "id": "msgraph-calendar",
  "version": "1.0",
  "name": "Microsoft Calendar",
  "names": [
    {
      "locale": "en",
      "value": "Microsoft Calendar"
    },
    {
      "locale": "de",
      "value": "Microsoft Kalender"
    }
  ],
  "description": "Automate appointment organization and calendaring directly within your business processes.",
  "descriptions": [
    {
      "locale": "en",
      "value": "Automate appointment organization and calendaring directly within your business processes."
    },
    {
      "locale": "de",
      "value": "Automatisiere die Organisation von Terminen und Kalenderverwaltung direkt in deinen Geschäftsabläufen."
    }
  ],
  "type": "utils",
  "platformReview": "4.5",
  "sourceUrl": "https://github.com/axonivy-market/msgraph-connector",
  "language": "English",
  "industry": "Cross-Industry",
  "compatibility": "9.4+",
  "tags": ["office"],
  "mavenArtifacts": [
    {
      "repoUrl": "https://maven.axonivy.com",
      "name": "Microsoft Calendar Product",
      "groupId": "com.axonivy.connector.office365",
      "artifactId": "msgraph-calendar-product",
      "type": "zip"
    }
  ]
}

=== axonivy-market/market/market/connector/coffee-machine-connector/meta.json
{
  "$schema": "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
  "id": "coffee-machine-connector",
  "name": "Coffee Machine",
  "names": [
    {
      "locale": "en",
      "value": "Coffee Machine"
    },
    {
      "locale": "de",
      "value": "Coffee Machine"
    }
  ],
  "description": "This connector is part of our Onboarding Tutorial, which shows you how to use the Axon Ivy Designer.",
  "descriptions": [
    {
      "locale": "en",
      "value": "This connector is part of our Onboarding Tutorial, which shows you how to use the Axon Ivy Designer."
    },
    {
      "locale": "de",
      "value": "Dieser Connector ist Teil unseres Onboarding-Tutorials, das Ihnen zeigt, wie Sie den Axon Ivy Designer verwenden."
    }
  ],
  "type": "connector",
  "platformReview": "4.5",
  "sourceUrl": "https://github.com/axonivy-market/coffee-machine-connector",
  "statusBadgeUrl": "https://github.com/axonivy-market/coffee-machine-connector/actions/workflows/ci.yml/badge.svg",
  "language": "English",
  "industry": "Cross-Industry",
  "tags": ["tutorial"],
  "mavenArtifacts": [
    {
      "repoUrl": "https://maven.axonivy.com",
      "name": "Coffee Machine Connector",
      "groupId": "com.axonivy.connector.coffeemachine",
      "artifactId": "coffee-machine-connector-product",
      "type": "zip"
    }
  ]
}

=== axonivy-market/market/market/demos/master-detail/meta.json
{
    "$schema" : "https://json-schema.axonivy.com/market/10.0.2/meta.json",
    "id" : "master-detail-demo",
    "name" : "Master-Detail interface",
    "names" : [
        {
            "locale" : "en",
            "value" : "Master-Detail View"
        },
        {
            "locale" : "de",
            "value" : "Master-Detail Layout"
        }
    ],
    "description" : "Utilizing the Master-Detail pattern as a best practice.",
    "descriptions" : [
        {
            "locale" : "en",
            "value" : "Utilizing the Master-Detail pattern as a best practice for developping professional UI/UX."
        },
        {
            "locale" : "de",
            "value" : "Best-Practise f√ºr UI/UX Entwicklungen: Master-Detail Darstellung von Listeninformationen."
        }
    ],
    "type" : "solution",
    "platformReview" : "4.5",
    "sourceUrl" : "https://github.com/axonivy-market/master-detail",
    "statusBadgeUrl" : "https://github.com/axonivy-market/master-detail/actions/workflows/ci.yml/badge.svg",
    "language" : "English",
    "industry" : "Cross-Industry",
    "tags" : [
        "demo"
    ],
    "mavenArtifacts" : [
        {
            "name" : "Master Detail",
            "groupId" : "com.axonivy.demo.masterdetail",
            "artifactId" : "master-detail-product",
            "type" : "zip"
        },
        {
            "key" : "master-detail-demo",
            "name" : "Master-Detail interface Demo App",
            "groupId" : "com.axonivy.demo.masterdetail",
            "artifactId" : "master-detail-demo-app",
            "type" : "zip"
        }
    ]
}

=== axonivy-market/market/market/utils/custom-mail/meta.json
{
  "$schema": "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
  "id": "custom-mail-demo",
  "name": "Custom Mail Feature",
  "names": [
    {
      "locale": "en",
      "value": "Custom Mail Feature"
    },
    {
      "locale": "de",
      "value": "Standard Email"
    }
  ],
  "description": "Customize Axon Ivy standard mail notification using your own processes.",
  "descriptions": [
    {
      "locale": "en",
      "value": "Customize Axon Ivy standard mail notification using your own processes."
    },
    {
      "locale": "de",
      "value": "In dieser Demo wird gezeigt, wie die Standard-Mailbenachrichtigung von Axon Ivy an deine eigenen Prozesse angepasst wird."
    }
  ],
  "type": "utils",
  "platformReview": "4.5",
  "sourceUrl": "https://github.com/axonivy-market/custom-mail-demo",
  "statusBadgeUrl": "https://github.com/axonivy-market/custom-mail-demo/actions/workflows/ci.yml/badge.svg",
  "language": "English",
  "industry": "Cross-Industry",
  "tags": ["utils"],
  "mavenArtifacts": [
    {
      "name": "Custom Mail Demo Product",
      "groupId": "com.axonivy.demo.custom.mail",
      "artifactId": "custom-mail-demo-product",
      "type": "zip"
    }
  ]
}

=== axonivy-market/market/market/connector/sftp/meta.json
{
  "$schema": "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
  "id": "sftp-connector",
  "name": "SFTP",
  "names": [
    {
      "locale": "en",
      "value": "SFTP"
    },
    {
      "locale": "de",
      "value": "SFTP"
    }
  ],
  "description": "An SFTP client that securely transfers files to and from a remote computer using the SFTP protocol.",
  "descriptions": [
    {
      "locale": "en",
      "value": "An SFTP client that securely transfers files to and from a remote computer using the SFTP protocol."
    },
    {
      "locale": "de",
      "value": "Ein Client, der Dateien sicher zwischen Deinem lokalen und einem Remote-Computer, mit dem SFTP-Protokoll, überträgt."
    }
  ],
  "type": "connector",
  "platformReview": "4.5",
  "sourceUrl": "https://github.com/axonivy-market/sftp-connector",
  "statusBadgeUrl": "https://github.com/axonivy-market/sftp-connector/actions/workflows/ci.yml/badge.svg",
  "language": "English",
  "industry": "Cross-Industry",
  "tags": ["sftp"],
  "mavenArtifacts": [
    {
      "repoUrl": "https://maven.axonivy.com",
      "name": "SFTP Connector",
      "groupId": "com.axonivy.connector.sftp",
      "artifactId": "sftp-connector-product",
      "type": "zip"
    }
  ]
}

=== axonivy-market/market/market/utils/microsoft365/toDo/meta.json
{
  "$schema": "https://json-schema.axonivy.com/market/10.0.5/meta.json",
  "id": "msgraph-todo",
  "name": "Microsoft To Do",
  "names": [
    {
      "locale": "en",
      "value": "Microsoft To Do"
    },
    {
      "locale": "de",
      "value": "Microsoft To Do"
    }
  ],
  "description": "Organize and track Microsoft To Do task lists directly within your business processes.",
  "descriptions": [
    {
      "locale": "en",
      "value": "Organize and track Microsoft To Do task lists directly within your business processes."
    },
    {
      "locale": "de",
      "value": "Integriere Microsoft To Do mühelos mit deinen Geschäftsprozessen, um Aufgaben zentral zu steuern und nachzuverfolgen."
    }
  ],
  "type": "utils",
  "platformReview": "4.5",
  "sourceUrl": "https://github.com/axonivy-market/msgraph-connector",
  "language": "English",
  "industry": "Cross-Industry",
  "compatibility": "9.4+",
  "tags": ["office"],
  "mavenArtifacts": [
    {
      "repoUrl": "https://maven.axonivy.com",
      "name": "Microsoft ToDo Product",
      "groupId": "com.axonivy.connector.office365",
      "artifactId": "msgraph-todo-product",
      "type": "zip"
    }
  ]
}

=== axonivy-market/market/market/utils/aspose-barcode/meta.json
{
  "$schema": "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
  "id": "aspose-barcode-demo",
  "name": "Aspose.BarCode Demo",
  "names": [
    {
      "locale": "en",
      "value": "Aspose.BarCode Demo"
    },
    {
      "locale": "de",
      "value": "Aspose.BarCode Demo"
    }
  ],
  "description": "Create, & recognize barcodes of linear and 2D types within any business process.",
  "descriptions": [
    {
      "locale": "en",
      "value": "Create, & recognize barcodes of linear and 2D types within any business process."
    },
    {
      "locale": "de",
      "value": "Integriere die Erstellung und Erkennung von linearen und 2D-Barcodes in deine Geschäftsprozesse."
    }
  ],
  "type": "utils",
  "platformReview": "4.5",
  "sourceUrl": "https://github.com/axonivy-market/doc-factory",
  "statusBadgeUrl": "https://github.com/axonivy-market/doc-factory/actions/workflows/ci.yml/badge.svg",
  "language": "English",
  "industry": "Cross-Industry",
  "tags": ["utils", "barcode", "document generation"],
  "validate": true,
  "mavenArtifacts": [
    {
      "name": "Aspose.Barcode Demo Product",
      "groupId": "com.axonivy.utils.docfactory",
      "artifactId": "aspose-barcode-demo-product",
      "type": "zip"
    }
  ]
}
