=== axonivy-market/market/schema/meta.json
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "$defs" : {
    "ArchivedArtifact" : {
      "type" : "object",
      "properties" : {
        "artifactId" : {
          "type" : "string",
          "minLength" : "5"
        },
        "groupId" : {
          "type" : "string",
          "minLength" : "5"
        },
        "lastVersion" : {
          "type" : "string",
          "description" : "this is the 'max version' selector. All versions which are lower than or equal the defined value, will be treated as legacy artifact.\nTherefore supplying 'legacy' group-/artifact-id for download.\n",
          "minLength" : "5"
        }
      },
      "required" : [ "artifactId", "groupId", "lastVersion" ],
      "additionalProperties" : false
    },
    "ArtifactType" : {
      "type" : "string",
      "enum" : [ "zip", "nbm", "jar" ]
    },
    "Cost" : {
      "type" : "string",
      "enum" : [ "free", "paid" ]
    },
    "DisplayDescription" : {
      "type" : "object",
      "properties" : {
        "locale" : {
          "minLength" : "2",
          "additionalProperties" : false,
          "type" : "string",
          "examples" : [ "{'de', 'en'}" ]
        },
        "value" : {
          "type" : "string",
          "minLength" : "5",
          "maxLength" : "200"
        }
      },
      "required" : [ "locale", "value" ],
      "additionalProperties" : false
    },
    "DisplayName" : {
      "type" : "object",
      "properties" : {
        "locale" : {
          "minLength" : "2",
          "additionalProperties" : false,
          "type" : "string",
          "examples" : [ "{'de', 'en'}" ]
        },
        "value" : {
          "type" : "string",
          "minLength" : "1",
          "maxLength" : "30"
        }
      },
      "required" : [ "locale", "value" ],
      "additionalProperties" : false
    },
    "MavenArtifact" : {
      "type" : "object",
      "properties" : {
        "archivedArtifacts" : {
          "description" : "archived artifacts using old (legacy) group ID and artifact ID with the last version they were being used.",
          "type" : "array",
          "items" : {
            "$ref" : "#/$defs/ArchivedArtifact"
          },
          "examples" : [ " \t\t\"archivedArtifacts\": [\n\t{\n\t\t\"lastVersion\": \"10.0.0\",\n\t\t\"groupId\": \"com.axonivy.connector.twitter\",\n\t\t\"artifactId\": \"twitter-connector\"\n\t}\n]\n" ]
        },
        "artifactId" : {
          "type" : "string",
          "minLength" : "5"
        },
        "doc" : {
          "type" : "boolean"
        },
        "groupId" : {
          "type" : "string",
          "minLength" : "5"
        },
        "key" : {
          "type" : "string"
        },
        "makesSenseAsMavenDependency" : {
          "type" : "boolean"
        },
        "name" : {
          "type" : "string",
          "minLength" : "5"
        },
        "repoUrl" : {
          "type" : "string"
        },
        "type" : {
          "$ref" : "#/$defs/ArtifactType"
        }
      },
      "required" : [ "artifactId", "groupId", "name" ],
      "additionalProperties" : false
    },
    "Type" : {
      "type" : "string",
      "enum" : [ "connector", "demo", "utils", "solution" ]
    }
  },
  "type" : "object",
  "properties" : {
    "$schema" : {
      "type" : "string"
    },
    "compatibility" : {
      "type" : "string",
      "pattern" : "^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)[+]?$"
    },
    "contactUs" : {
      "type" : "boolean",
      "description" : "shows the link to contact axonivy"
    },
    "cost" : {
      "$ref" : "#/$defs/Cost"
    },
    "deprecated" : {
      "type" : "boolean"
    },
    "description" : {
      "type" : "string",
      "minLength" : "5",
      "maxLength" : "200"
    },
    "descriptions" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/$defs/DisplayDescription"
      }
    },
    "id" : {
      "type" : "string",
      "minLength" : "5",
      "maxLength" : "30"
    },
    "industry" : {
      "minLength" : "2",
      "additionalProperties" : false,
      "type" : "string",
      "examples" : [ "Cross-Industry" ]
    },
    "installMatcher" : {
      "type" : "string",
      "examples" : [ "best-match" ]
    },
    "language" : {
      "type" : "string",
      "examples" : [ "English" ]
    },
    "listed" : {
      "type" : "boolean"
    },
    "mavenArtifacts" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/$defs/MavenArtifact"
      }
    },
    "name" : {
      "type" : "string",
      "minLength" : "4",
      "maxLength" : "24"
    },
    "names" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/$defs/DisplayName"
      }
    },
    "platformReview" : {
      "type" : "string",
      "pattern" : "^([0-4])?(\\.[5])?$|^5$"
    },
    "sourceUrl" : {
      "type" : "string",
      "format" : "uri",
      "examples" : [ "https://github.com/axonivy-market/acme-connector" ]
    },
    "statusBadgeUrl" : {
      "type" : "string",
      "format" : "uri",
      "examples" : [ "https://github.com/axonivy-market/acme-connector/actions/workflows/ci.yml/badge.svg" ]
    },
    "tags" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "type" : {
      "$ref" : "#/$defs/Type"
    },
    "validate" : {
      "type" : "boolean"
    },
    "vendor" : {
      "type" : "string",
      "minLength" : "3"
    },
    "vendorImage" : {
      "type" : "string",
      "description" : "relative path to a logo of the vendor, e.g. 'acme.png'"
    },
    "vendorImageDarkMode" : {
      "type" : "string",
      "description" : "relative path to a logo of the vendor dark mode, e.g. 'acme-dark-mode.png'"
    },
    "vendorLogo" : {
      "type" : "string",
      "description" : "relative path to a badge of the vendor, e.g. 'bagde.png'"
    },
    "vendorLogoDarkMode" : {
      "type" : "string",
      "description" : "relative path to a badge of the vendor dark mode, e.g. 'bagde-dark.png'"
    },
    "vendorUrl" : {
      "type" : "string",
      "format" : "uri",
      "description" : "public accessible URI representating the vendor"
    },
    "version" : {
      "type" : "string",
      "pattern" : "^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$"
    },
    "versionDisplay" : {
      "type" : "string"
    }
  },
  "required" : [ "description", "id", "name", "type" ],
  "additionalProperties" : false
}

=== axonivy-market/market/market/connector/x-connector/meta.json
{
  "$schema": "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
  "id": "x-connector",
  "version": "1.0",
  "name": "X   ",
  "names": [
    {
      "locale": "en",
      "value": "X   "
    },
    {
      "locale": "de",
      "value": "X   "
    }
  ],
  "description": "The X API enables seamless message posting and interaction within the X network.",
  "descriptions": [
    {
      "locale": "en",
      "value": "The X API enables seamless message posting and interaction within the X network."
    },
    {
      "locale": "de",
      "value": "Die X API ermöglicht Interaktionen in diesem sozialen Neztwerk direkt aus deinen Geschäftsprozessen heraus."
    }
  ],
  "type": "connector",
  "platformReview": "4.5",
  "sourceUrl": "https://github.com/axonivy-market/x-connector",
  "statusBadgeUrl": "https://github.com/axonivy-market/x-connector/actions/workflows/ci.yml/badge.svg",
  "language": "English",
  "industry": "Cross-Industry",
  "compatibility": "9.2+",
  "tags": ["social"],
  "mavenArtifacts": [
    {
      "repoUrl": "https://maven.axonivy.com",
      "name": "X Connector Product",
      "groupId": "com.axonivy.connector.x",
      "artifactId": "x-connector-product",
      "type": "zip"
    },
    {
      "name": "X Connector",
      "groupId": "com.axonivy.connector.x",
      "artifactId": "x-connector",
      "archivedArtifacts": [
        {
          "lastVersion": "10.0.0",
          "groupId": "com.axonivy.connector.twitter",
          "artifactId": "twitter-connector"
        }
      ]
    }
  ]
}

=== axonivy-market/market/market/connector/azure-servicebus-connector/meta.json
{
  "$schema": "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
  "id": "azure-servicebus-connector",
  "name": "Azure Service Bus",
  "names": [
    {
      "locale": "en",
      "value": "Azure Service Bus"
    },
    {
      "locale": "de",
      "value": "Azure Service Bus"
    }
  ],
  "description": "This connector integrates Azure Service Bus into your Axon Ivy application and supports connections for sending and receiving messages.",
  "descriptions": [
    {
      "locale": "en",
      "value": "This connector integrates Azure Service Bus into your Axon Ivy application and supports connections for sending and receiving messages."
    },
    {
      "locale": "de",
      "value": "Dieser Konnektor integriert den Azure Service Bus in Deine Axon Ivy Anwendung und unterstützt das Senden und Empfangen von Nachrichten."
    }
  ],
  "type": "connector",
  "platformReview": "4.5",
  "sourceUrl": "https://github.com/axonivy-market/azure-servicebus-connector",
  "statusBadgeUrl": "https://github.com/axonivy-market/azure-servicebus-connector/actions/workflows/ci.yml/badge.svg",
  "language": "English",
  "industry": "Cross-Industry",
  "tags": ["Cloud"],
  "mavenArtifacts": [
    {
      "repoUrl": "https://maven.axonivy.com",
      "name": "Azure Servicebus Connector Product",
      "groupId": "com.axonivy.connector.azure.servicebus",
      "artifactId": "azure-servicebus-connector-product",
      "type": "zip"
    }
  ]
}

=== axonivy-market/market/market/connector/vertexai-google/meta.json
{
  "$schema": "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
  "id": "vertexai-google",
  "name": "Vertex AI Google",
  "names": [
    {
      "locale": "en",
      "value": "Vertex AI Google "
    },
    {
      "locale": "de",
      "value": "Vertex AI Google"
    }
  ],
	"description": "Vertex AI Gemini is Google's cutting-edge AI model for seamless visual and text processing.",
	"descriptions": [
    {
      "locale": "en",
      "value": "Vertex AI Gemini is Google's cutting-edge AI model for seamless visual and text processing."
    },
    {
      "locale": "de",
      "value": "Vertex AI Gemini ist Googles innovatives KI-Modell für intelligente Bild- und Textverarbeitung."
    }
  ],
  "type": "connector",
  "platformReview": "4.5",
  "sourceUrl": "https://github.com/axonivy-market/vertexai-google",
  "statusBadgeUrl": "https://github.com/axonivy-market/vertexai-google/actions/workflows/ci.yml/badge.svg",
  "language": "English",
  "industry": "Cross-Industry",
  "tags": ["connector"],
  "mavenArtifacts": [
    {
      "repoUrl": "https://maven.axonivy.com",
      "name": "VertexAi Google Product",
      "groupId": "com.axonivy.connector.vertexai",
      "artifactId": "vertexai-google-product",
      "type": "zip"
    }
  ]
}

=== axonivy-market/market/market/demo/connectivity/meta.json
{
  "$schema": "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
  "id": "connectivity-demo",
  "name": "Connectivity Features",
  "names": [
    {
      "locale": "en",
      "value": "Connectivity Features"
    },
    {
      "locale": "de",
      "value": "Integration von Drittsystemen"
    }
  ],
  "description": "Explore various 3rd party integrations based on web service technologies.",
  "descriptions": [
    {
      "locale": "en",
      "value": "Explore various 3rd party integrations based on web service technologies."
    },
    {
      "locale": "de",
      "value": "Verschiedene Integrationen von Drittanbietern basierend auf Web-Service-Technologien in einer Demo zusammengefasst."
    }
  ],
  "type": "demo",
  "platformReview": "4.5",
  "sourceUrl": "https://github.com/axonivy-market/demo-projects",
  "statusBadgeUrl": "https://github.com/axonivy-market/demo-projects/actions/workflows/ci.yml/badge.svg",
  "language": "English",
  "industry": "Cross-Industry",
  "tags": ["demo"],
  "validate": true,
  "mavenArtifacts": [
    {
      "name": "Connectivity Demos Product",
      "groupId": "com.axonivy.demo",
      "artifactId": "connectivity-demos-product",
      "type": "zip"
    }
  ]
}

=== axonivy-market/market/market/connector/adobe-esign-connector/meta.json
{
    "$schema": "https://json-schema.axonivy.com/market/10.0.0/meta.json",
    "id": "adobe-esign-connector",
    "name": "Adobe Esign Connector",
    "description": "Use this connector to create, sign document with Adobe Sign.",
    "type": "connector",
    "platformReview": "4.5",
    "sourceUrl": "https://github.com/axonivy-market/adobe-esign-connector",
    "statusBadgeUrl": "https://github.com/axonivy-market/adobe-esign-connector/actions/workflows/ci.yml/badge.svg",
    "language": "English",
    "industry": "Cross-Industry",
    "tags": [ "container" ],
    "mavenArtifacts": [
        {
            "repoUrl": "https://maven.axonivy.com",
            "name": "Adobe Esign Connector",
            "groupId": "com.axonivy.market",
            "artifactId": "adobe-esign-connector-product",
            "type": "zip"
        }
    ]
}

=== axonivy-market/market/market/connector/idp-connector/meta.json
{
    "$schema": "https://json-schema.axonivy.com/market/10.0.2/meta.json",
    "id": "idp-connector",
    "name": "Axon Ivy IDP",
    "names": [
        {
            "locale": "en",
            "value": "Axon Ivy IDP"
        },
        {
            "locale": "de",
            "value": "Axon Ivy IDP"
        }
    ],
    "description": "Axon Ivy IDP is a powerful Intelligent Document Processing solution, transforming document-intensive processes into streamlined, efficient workflows.",
    "descriptions": [
        {
            "locale": "en",
            "value": "Axon Ivy IDP is a powerful Intelligent Document Processing solution, transforming document-intensive processes into streamlined, efficient workflows."
        },
        {
            "locale": "de",
            "value": "Axon Ivy IDP ist eine umfassende Lösung für die intelligente Dokumentenverarbeitung, die dokumentenintensive Prozesse in schlanke, effiziente Workflows verwandelt."
        }
    ],
    "type": "connector",
    "platformReview": "4.5",
    "sourceUrl": "https://github.com/axonivy-market/idp-connector",
    "statusBadgeUrl": "https://github.com/axonivy-market/idp-connector/actions/workflows/ci.yml/badge.svg",
    "language": "English",
    "industry": "Cross-Industry",
    "tags": ["AI"],
    "mavenArtifacts": [
        {
            "repoUrl": "https://maven.axonivy.com",
            "name": "IDP Connector Product",
            "groupId": "com.axonivy.connector.idp",
            "artifactId": "idp-connector-product",
            "type": "zip"
        }
    ]
}

=== axonivy-market/market/market/connector/sproof-connector/meta.json
{
  "$schema": "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
  "id": "sproof-connector",
  "name": "Sproof",
  "names": [
    {
      "locale": "en",
      "value": "Sproof"
    },
    {
      "locale": "de",
      "value": "Sproof"
    }
  ],
  "description": "Sproof powers secure, end-to-end digital signature workflows fully integrated with Axon Ivy.",
  "descriptions": [
    {
      "locale": "en",
      "value": "Sproof powers secure, end-to-end digital signature workflows fully integrated with Axon Ivy."
    },
    {
      "locale": "de",
      "value": "Sproof ermöglicht sichere, durchgängige Workflows für digitale Signaturen, die vollständig in Axon Ivy integriert sind."
    }
  ],
  "type": "connector",
  "platformReview": "4",
  "sourceUrl": "https://github.com/axonivy-market/sproof-connector",
  "statusBadgeUrl": "https://github.com/axonivy-market/sproof-connector/actions/workflows/ci.yml/badge.svg",
  "language": "English",
  "industry": "Cross-Industry",
  "tags": ["connector"],
  "mavenArtifacts": [
    {
      "repoUrl": "https://maven.axonivy.com",
      "name": "Sproof Product",
      "artifactId": "sproof-connector-product",
      "groupId": "com.axonivy.connector.sproof",
      "type": "zip"
    }
  ]
}

=== axonivy-market/market/market/connector/threema-connector/meta.json
{
  "$schema": "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
  "id": "threema-connector",
  "name": "Threema",
  "names": [
    {
      "locale": "en",
      "value": "Threema"
    },
    {
      "locale": "de",
      "value": "Threema"
    }
  ],
  "description": "Use the Threema API to send secure messages directly from your business processes.",
  "descriptions": [
    {
      "locale": "en",
      "value": "Use the Threema API to send secure messages directly from your business processes."
    },
    {
      "locale": "de",
      "value": "Verwende die Threema API, um verschlüsselte Nachrichten direkt aus deinen Geschäftsabläufen an diesen Messenger zu senden."
    }
  ],
  "type": "connector",
  "platformReview": "5",
  "sourceUrl": "https://github.com/axonivy-market/threema-connector",
  "statusBadgeUrl": "https://github.com/axonivy-market/threema-connector/actions/workflows/ci.yml/badge.svg",
  "language": "English",
  "industry": "Cross-Industry",
  "tags": ["communication"],
  "mavenArtifacts": [
    {
      "repoUrl": "https://maven.axonivy.com",
      "name": "Threema Connector",
      "groupId": "com.axonivy.connector.threema",
      "artifactId": "threema-connector-product",
      "type": "zip"
    }
  ]
}
