=== axonivy-market/market/schema/meta.json
{
  "$schema" : "https://json-schema.org/draft/2019-09/schema",
  "$defs" : {
    "ArchivedArtifact" : {
      "type" : "object",
      "properties" : {
        "artifactId" : {
          "type" : "string",
          "minLength" : "5"
        },
        "groupId" : {
          "type" : "string",
          "minLength" : "5"
        },
        "lastVersion" : {
          "type" : "string",
          "description" : "this is the 'max version' selector. All versions which are lower than or equal the defined value, will be treated as legacy artifact.\nTherefore supplying 'legacy' group-/artifact-id for download.\n",
          "minLength" : "5"
        }
      },
      "required" : [ "artifactId", "groupId", "lastVersion" ],
      "additionalProperties" : false
    },
    "ArtifactType" : {
      "type" : "string",
      "enum" : [ "zip", "nbm", "jar" ]
    },
    "Cost" : {
      "type" : "string",
      "enum" : [ "free", "paid" ]
    },
    "DisplayDescription" : {
      "type" : "object",
      "properties" : {
        "locale" : {
          "minLength" : "2",
          "additionalProperties" : false,
          "type" : "string",
          "examples" : [ "{'de', 'en'}" ]
        },
        "value" : {
          "type" : "string",
          "minLength" : "5",
          "maxLength" : "200"
        }
      },
      "required" : [ "locale", "value" ],
      "additionalProperties" : false
    },
    "DisplayName" : {
      "type" : "object",
      "properties" : {
        "locale" : {
          "minLength" : "2",
          "additionalProperties" : false,
          "type" : "string",
          "examples" : [ "{'de', 'en'}" ]
        },
        "value" : {
          "type" : "string",
          "minLength" : "1",
          "maxLength" : "30"
        }
      },
      "required" : [ "locale", "value" ],
      "additionalProperties" : false
    },
    "MavenArtifact" : {
      "type" : "object",
      "properties" : {
        "archivedArtifacts" : {
          "description" : "archived artifacts using old (legacy) group ID and artifact ID with the last version they were being used.",
          "type" : "array",
          "items" : {
            "$ref" : "#/$defs/ArchivedArtifact"
          },
          "examples" : [ " \t\t\"archivedArtifacts\": [\n\t{\n\t\t\"lastVersion\": \"10.0.0\",\n\t\t\"groupId\": \"com.axonivy.connector.twitter\",\n\t\t\"artifactId\": \"twitter-connector\"\n\t}\n]\n" ]
        },
        "artifactId" : {
          "type" : "string",
          "minLength" : "5"
        },
        "doc" : {
          "type" : "boolean"
        },
        "groupId" : {
          "type" : "string",
          "minLength" : "5"
        },
        "key" : {
          "type" : "string"
        },
        "makesSenseAsMavenDependency" : {
          "type" : "boolean"
        },
        "name" : {
          "type" : "string",
          "minLength" : "5"
        },
        "repoUrl" : {
          "type" : "string"
        },
        "type" : {
          "$ref" : "#/$defs/ArtifactType"
        }
      },
      "required" : [ "artifactId", "groupId", "name" ],
      "additionalProperties" : false
    },
    "Type" : {
      "type" : "string",
      "enum" : [ "connector", "demo", "utils", "solution" ]
    }
  },
  "type" : "object",
  "properties" : {
    "$schema" : {
      "type" : "string"
    },
    "compatibility" : {
      "type" : "string",
      "pattern" : "^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)[+]?$"
    },
    "contactUs" : {
      "type" : "boolean",
      "description" : "shows the link to contact axonivy"
    },
    "cost" : {
      "$ref" : "#/$defs/Cost"
    },
    "deprecated" : {
      "type" : "boolean"
    },
    "description" : {
      "type" : "string",
      "minLength" : "5",
      "maxLength" : "200"
    },
    "descriptions" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/$defs/DisplayDescription"
      }
    },
    "id" : {
      "type" : "string",
      "minLength" : "5",
      "maxLength" : "30"
    },
    "industry" : {
      "minLength" : "2",
      "additionalProperties" : false,
      "type" : "string",
      "examples" : [ "Cross-Industry" ]
    },
    "installMatcher" : {
      "type" : "string",
      "examples" : [ "best-match" ]
    },
    "language" : {
      "type" : "string",
      "examples" : [ "English" ]
    },
    "listed" : {
      "type" : "boolean"
    },
    "mavenArtifacts" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/$defs/MavenArtifact"
      }
    },
    "name" : {
      "type" : "string",
      "minLength" : "4",
      "maxLength" : "24"
    },
    "names" : {
      "type" : "array",
      "items" : {
        "$ref" : "#/$defs/DisplayName"
      }
    },
    "platformReview" : {
      "type" : "string",
      "pattern" : "^([0-4])?(\\.[5])?$|^5$"
    },
    "sourceUrl" : {
      "type" : "string",
      "format" : "uri",
      "examples" : [ "https://github.com/axonivy-market/acme-connector" ]
    },
    "statusBadgeUrl" : {
      "type" : "string",
      "format" : "uri",
      "examples" : [ "https://github.com/axonivy-market/acme-connector/actions/workflows/ci.yml/badge.svg" ]
    },
    "tags" : {
      "type" : "array",
      "items" : {
        "type" : "string"
      }
    },
    "type" : {
      "$ref" : "#/$defs/Type"
    },
    "validate" : {
      "type" : "boolean"
    },
    "vendor" : {
      "type" : "string",
      "minLength" : "3"
    },
    "vendorImage" : {
      "type" : "string",
      "description" : "relative path to a logo of the vendor, e.g. 'acme.png'"
    },
    "vendorImageDarkMode" : {
      "type" : "string",
      "description" : "relative path to a logo of the vendor dark mode, e.g. 'acme-dark-mode.png'"
    },
    "vendorLogo" : {
      "type" : "string",
      "description" : "relative path to a badge of the vendor, e.g. 'bagde.png'"
    },
    "vendorLogoDarkMode" : {
      "type" : "string",
      "description" : "relative path to a badge of the vendor dark mode, e.g. 'bagde-dark.png'"
    },
    "vendorUrl" : {
      "type" : "string",
      "format" : "uri",
      "description" : "public accessible URI representating the vendor"
    },
    "version" : {
      "type" : "string",
      "pattern" : "^(\\d+\\.)?(\\d+\\.)?(\\*|\\d+)$"
    },
    "versionDisplay" : {
      "type" : "string"
    }
  },
  "required" : [ "description", "id", "name", "type" ],
  "additionalProperties" : false
}

=== axonivy-market/market/market/utils/persistence-utils/meta.json
{
  "$schema": "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
  "id": "persistence-utils",
  "name": "Persistence Utils",
  "names": [
    {
      "locale": "en",
      "value": "Persistence Utils"
    },
    {
      "locale": "de",
      "value": "Persistenz Utilities"
    }
  ],
  "description": "Axon Ivy's Persistence Utility facilitates the automation of processes by introducing a DAO abstraction layer.",
  "descriptions": [
    {
      "locale": "en",
      "value": "Axon Ivy's Persistence Utility facilitates the automation of processes by introducing a DAO abstraction layer."
    },
    {
      "locale": "de",
      "value": "Axon Ivys Persistence Lib Utility erleichtert die Automatisierung von Prozessen durch die Einführung einer DAO-Abstraktionsebene."
    }
  ],
  "type": "utils",
  "platformReview": "4.5",
  "sourceUrl": "https://github.com/axonivy-market/persistence-utils",
  "statusBadgeUrl": "https://github.com/axonivy-market/persistence-utils/actions/workflows/ci.yml/badge.svg",
  "language": "English",
  "industry": "Cross-Industry",
  "tags": ["utils"],
  "mavenArtifacts": [
    {
      "repoUrl": "https://maven.axonivy.com",
      "name": "Persistence Utils Product",
      "groupId": "com.axonivy.utils.persistence",
      "artifactId": "persistence-utils-product",
      "type": "zip"
    }
  ]
}

=== axonivy-market/market/market/utils/pdf-box/meta.json
{
  "$schema": "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
  "id": "pdfbox-utils",
  "name": "PDFBox Utils",
  "names": [
    {
      "locale": "en",
      "value": "PDFBox Utils"
    },
    {
      "locale": "de",
      "value": "PDFBox Utils"
    }
  ],
  "description": "A lightweight PDF utility for Axon Ivy that simplifies PDF filling and PDF-to-image conversion.",
  "descriptions": [
    {
      "locale": "en",
      "value": "A lightweight PDF utility for Axon Ivy that simplifies PDF filling and PDF-to-image conversion."
    },
    {
      "locale": "de",
      "value": "Ein kompaktes PDF-Werkzeug für Axon Ivy, das das Befüllen von PDFs sowie die Umwandlung von PDFs in Bildformate vereinfacht."
    }
  ],
  "type": "utils",
  "platformReview": "4.5",
  "sourceUrl": "https://github.com/axonivy-market/pdf-box",
  "statusBadgeUrl": "https://github.com/axonivy-market/pdf-box/actions/workflows/ci.yml/badge.svg",
  "language": "English",
  "industry": "Cross-Industry",
  "tags": ["utils"],
  "mavenArtifacts": [
    {
      "name": "PDFBox Utils Product",
      "groupId": "com.axonivy.utils.pdfbox",
      "artifactId": "pdf-box-product",
      "type": "zip",
      "repoUrl": "https://maven.axonivy.com"
    }
  ]
}

=== axonivy-market/market/market/connector/deepl-connector/meta.json
{
  "$schema": "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
  "id": "deepl-connector",
  "name": "DeepL",
  "names": [
    {
      "locale": "en",
      "value": "DeepL"
    },
    {
      "locale": "de",
      "value": "DeepL"
    }
  ],
  "description": "Easily integrate and manage real-time language translation services within your business processes.",
  "descriptions": [
    {
      "locale": "en",
      "value": "Easily integrate and manage real-time language translation services within your business processes."
    },
    {
      "locale": "de",
      "value": "Einfache Integration und Verwaltung von Übersetzungsdiensten in deinen Geschäftsprozessen."
    }
  ],
  "type": "connector",
  "platformReview": "4.5",
  "sourceUrl": "https://github.com/axonivy-market/deepl-connector",
  "statusBadgeUrl": "https://github.com/axonivy-market/deepl-connector/actions/workflows/ci.yml/badge.svg",
  "language": "English",
  "industry": "Cross-Industry",
  "tags": ["AI"],
  "mavenArtifacts": [
    {
      "repoUrl": "https://maven.axonivy.com",
      "name": "DeepL connector",
      "groupId": "com.axonivy.connector.deepl",
      "artifactId": "deepl-connector-product",
      "type": "zip"
    }
  ]
}

=== axonivy-market/market/market/connector/openai-assistant/meta.json
{
  "$schema": "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
  "id": "openai-assistant",
  "name": "ChatGPT Assistant",
  "names": [
    {
      "locale": "en",
      "value": "ChatGPT Assistant"
    },
    {
      "locale": "de",
      "value": "ChatGPT Assistent"
    }
  ],
  "description": "The ChatGPT assistant explains, maintains and extends code for you",
  "descriptions": [
    {
      "locale": "en",
      "value": "The ChatGPT assistant explains, maintains and extends code for you"
    },
    {
      "locale": "de",
      "value": "Der ChatGPT Assistent erklärt und erweitert Axon Ivy Code für Dich."
    }
  ],
  "type": "connector",
  "platformReview": "4.5",
  "sourceUrl": "https://github.com/axonivy-market/openai-connector",
  "statusBadgeUrl": "https://github.com/axonivy-market/openai-connector/actions/workflows/ci.yml/badge.svg",
  "language": "English",
  "industry": "Cross-Industry",
  "tags": ["AI"],
  "mavenArtifacts": [
    {
      "repoUrl": "https://maven.axonivy.com",
      "name": "OpenAI Assistant",
      "groupId": "com.axonivy.connector.openai",
      "artifactId": "openai-assistant-product",
      "type": "zip"
    }
  ]
}

=== axonivy-market/market/market/connector/azure-blob-storage/meta.json
{
  "$schema": "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
  "id": "azure-blob-storage",
  "name": "Azure Blob Storage",
  "names": [
    {
      "locale": "en",
      "value": "Azure Blob Storage"
    },
    {
      "locale": "de",
      "value": "Azure Blob Storage"
    }
  ],
  "description": "Introducing our new connector for Azure Blob Storage, enabling seamless integration directly from your applications.",
  "descriptions": [
    {
      "locale": "en",
      "value": "Introducing our new connector for Azure Blob Storage, enabling seamless integration directly from your applications."
    },
    {
      "locale": "de",
      "value": "Nutze unseren neuen Konnektor für Azure Blob Storage und integriere deine gespeicherten Daten mit wenigen Klicks."
    }
  ],
  "type": "connector",
  "platformReview": "4.5",
  "sourceUrl": "https://github.com/axonivy-market/azure-blob-connector",
  "statusBadgeUrl": "https://github.com/axonivy-market/azure-blob-connector/actions/workflows/ci.yml/badge.svg",
  "language": "English",
  "industry": "Cross-Industry",
  "tags": ["Cloud"],
  "mavenArtifacts": [
    {
      "repoUrl": "https://maven.axonivy.com",
      "name": "Azure Blob Connector Product",
      "groupId": "com.axonivy.connector.azure.blob",
      "artifactId": "azure-blob-connector-product",
      "type": "zip"
    }
  ]
}

=== axonivy-market/market/market/connector/metaproc/meta.json
{
	"id": "metaproc-connector",
	"name": "Axon Ivy RPA",
	"description": "Built-In Robotic Process Automation (RPA)",
	"type": "connector",
	"platformReview": "4.5",
	"sourceUrl": "https://github.com/axonivy-market/metaproc-connector",
	"statusBadgeUrl": "https://github.com/axonivy-market/metaproc-connector/actions/workflows/ci.yml/badge.svg",
	"language": "English",
	"industry": "Cross-Industry",
	"tags": ["RPA"],
	"mavenArtifacts": [
		{
			"repoUrl": "https://maven.axonivy.com",
			"name": "meta:proc Connector Product",
			"groupId": "com.axonivy.connector.metaproc",
			"artifactId": "metaproc-connector-product",
			"type": "zip"
		}
	]
}

=== axonivy-market/market/market/connector/kafka-connector/meta.json
{
  "$schema": "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
  "id": "kafka-connector",
  "name": "Apache Kafka",
  "names": [
    {
      "locale": "en",
      "value": "Apache Kafka"
    },
    {
      "locale": "de",
      "value": "Apache Kafka"
    }
  ],
  "description": "API for facilitating distributed event streaming to automate real-time process workflows.",
  "descriptions": [
    {
      "locale": "en",
      "value": "API for facilitating distributed event streaming to automate real-time process workflows."
    },
    {
      "locale": "de",
      "value": "Diese API erleichtert das verteilte Event-Streaming bei der Automatisierung von Echtzeit-Prozess-Workflows."
    }
  ],
  "type": "connector",
  "platformReview": "4.5",
  "sourceUrl": "https://github.com/axonivy-market/kafka-connector",
  "statusBadgeUrl": "https://github.com/axonivy-market/kafka-connector/actions/workflows/ci.yml/badge.svg",
  "language": "English",
  "industry": "Cross-Industry",
  "tags": ["messaging"],
  "mavenArtifacts": [
    {
      "name": "Kafka Connector Product",
      "groupId": "com.axonivy.connector.kafka",
      "artifactId": "kafka-connector-product",
      "type": "zip"
    }
  ]
}

=== axonivy-market/market/market/utils/ivy-load-test/meta.json
{
  "$schema": "https://raw.githubusercontent.com/axonivy-market/market/refs/heads/master/schema/meta.json",
  "id": "ivy-load-test",
  "name": "Ivy Load Test",
  "names": [
    {
      "locale": "en",
      "value": "Ivy Load Test"
    },
    {
      "locale": "de",
      "value": "Ivy Load Test"
    }
  ],
  "description": "This demo shows how to run performance tests for Axon Ivy projects using the JMeter Java DSL.",
  "descriptions": [
    {
      "locale": "en",
      "value": "This demo shows how to run performance tests for Axon Ivy projects using the JMeter Java DSL."
    },
    {
      "locale": "de",
      "value": "Diese Demo zeigt die Umsetzung von Performance-Tests für Axon Ivy-Projekte mithilfe von JMeter Java DSL."
    }
  ],
  "type": "utils",
  "platformReview": "4.5",
  "sourceUrl": "https://github.com/axonivy-market/ivy-load-test",
  "statusBadgeUrl": "https://github.com/axonivy-market/ivy-load-test/actions/workflows/ci.yml/badge.svg",
  "language": "English",
  "industry": "Cross-Industry",
  "tags": ["utils"],
  "validate": true,
  "mavenArtifacts": [
    {
      "name": "Ivy Load Test Product",
      "groupId": "com.axonivy.utils.loadtest",
      "artifactId": "ivy-load-test-product",
      "type": "zip",
      "archivedArtifacts": [
        {
          "lastVersion": "13.2.0",
          "groupId": "com.axonivy.demo.loadtest",
          "artifactId": "ivy-load-test-product"
        }
      ]
    }
  ]
}
